FROM golang:1.25 AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /usr/local/bin/app .

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
WORKDIR /usr/src/app
COPY config.toml config.toml
COPY --from=builder /usr/local/bin/app /usr/local/bin/app

CMD ["app"]
